name: tickea
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^13.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  table_calendar: ^3.1.2
  provider: ^6.1.5+1
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: RedHatMono
      fonts:
        - asset: assets/fonts/Red_Hat_Mono/static/RedHatMono-Regular.ttf


