name: tickea
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

